[package]
name = "dioxus-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/TeFiLeDo/dioxus" }
dioxus-router = { git = "https://github.com/TeFiLeDo/dioxus" }
dioxus-web = { git = "https://github.com/TeFiLeDo/dioxus" }
wasm-logger = "0.2"
